# Generated by Django 3.1.7 on 2021-03-28 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0004_userinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelinfo',
            name='author',
            field=models.CharField(max_length=200, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='novelinfo',
            name='keywords',
            field=models.CharField(default='', max_length=1000, verbose_name='关键词'),
        ),
        migrations.AlterField(
            model_name='novelinfo',
            name='name',
            field=models.CharField(max_length=200, verbose_name='小说名'),
        ),
        migrations.CreateModel(
            name='NovelWordCloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.TextField(verbose_name='小说词频')),
                ('novelId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.novelinfo', verbose_name='小说id')),
            ],
            options={
                'verbose_name_plural': '小说词频表',
            },
        ),
    ]
