# Generated by Django 3.1.7 on 2021-03-28 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0005_auto_20210328_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovelRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(default='', max_length=1000, verbose_name='关键词')),
                ('read_time', models.DateTimeField(auto_now_add=True, verbose_name='阅读时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.authuser', verbose_name='用户id')),
            ],
            options={
                'verbose_name_plural': '小说阅读表',
            },
        ),
    ]
