# Generated by Django 3.1.7 on 2021-04-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0006_novelread'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelcontent',
            name='read_counts',
            field=models.IntegerField(default=0, verbose_name='阅读次数'),
        ),
        migrations.AddField(
            model_name='novelinfo',
            name='read_counts',
            field=models.IntegerField(default=0, verbose_name='阅读次数'),
        ),
    ]
