# Generated by Django 3.1.7 on 2021-04-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0008_auto_20210401_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordForbid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(default='', max_length=1000, verbose_name='关键词')),
            ],
            options={
                'verbose_name_plural': '词语屏蔽表',
            },
        ),
    ]
