# Generated by Django 3.1.7 on 2021-04-01 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0009_wordforbid'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovelCollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_time', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.novelinfo', verbose_name='小说')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.authuser', verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '小说收藏表',
            },
        ),
    ]
